export default {
  '__schema': {
    'types': [{
      'kind': 'OBJECT',
      'name': 'Query',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Bookmark',
      'possibleTypes': null
    }, {
      'kind': 'SCALAR',
      'name': 'ID',
      'possibleTypes': null
    }, {
      'kind': 'SCALAR',
      'name': 'Float',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'User',
      'possibleTypes': null
    }, {
      'kind': 'SCALAR',
      'name': 'String',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'ImageSizes',
      'possibleTypes': null
    }, {
      'kind': 'SCALAR',
      'name': 'Boolean',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Lesson',
      'possibleTypes': null
    }, {
      'kind': 'SCALAR',
      'name': 'Int',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Comment',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Course',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Favorite',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Issue',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Note',
      'possibleTypes': null
    }, {
      'kind': 'UNION',
      'name': 'Search',
      'possibleTypes': [{
        'name': 'Course'
      }, {
        'name': 'Lesson'
      }]
    }, {
      'kind': 'OBJECT',
      'name': 'Skill',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Mutation',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'UserCreate',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'UserAccessResponse',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'Error',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': 'RecoveryResponse',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'BookmarkCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'CommentCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'CommentSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'CourseCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'CourseSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'FavoriteCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'FavoriteSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'IssueCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'IssueSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'LessonCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'LessonSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'NoteCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'NoteSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'SkillCreate',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'SkillSet',
      'possibleTypes': null
    }, {
      'kind': 'INPUT_OBJECT',
      'name': 'UserSet',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': '__Schema',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': '__Type',
      'possibleTypes': null
    }, {
      'kind': 'ENUM',
      'name': '__TypeKind',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': '__Field',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': '__InputValue',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': '__EnumValue',
      'possibleTypes': null
    }, {
      'kind': 'OBJECT',
      'name': '__Directive',
      'possibleTypes': null
    }, {
      'kind': 'ENUM',
      'name': '__DirectiveLocation',
      'possibleTypes': null
    }]
  }
}
